Repository imsarahkhan/Group_3_Travel-Agency-Management-System, pull requests merged in 2021-12, with the labels that each got.

#30 Signup functionality issue
  Flow_Diagram.png
  README.md
  booking_output.png
  booking_sample.png
Labels: bug

#32 Create LICENSE
  LICENSE
Labels: documentation

#36 Discount Offer
  README.md
  images/book_flight_car.jpg
  images/book_flight_hotel.jpg
  images/book_hotel.jpg
  images/cancel_trip.jpg
  images/flight_hotel_car.jpg
  images/home.jpg
  images/login.jpg
  images/logout.jpg
  images/main_menu.jpg
  images/sign_up.jpg
  images/view_print_tricket.jpg
Labels: documentation, help wanted

#37 Document folder missing
  LICENSE
Labels: documentation

#38 Create main.yml for doxygen HTML link
  .github/workflows/main.yml
Labels: documentation
